import "../styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AppContext from "@/context/AppContext";
import Footer from "../components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${inter.className} min-h-screen flex flex-col sctroll`}>
				<AppContext>
					{children}
					<Footer />
				</AppContext>
			</body>
		</html>
	);
}
